[package]
name = "carrier-webui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
carrier-kernel = { workspace = true }
carrier-types = { workspace = true }
carrier-runtime = { workspace = true }
carrier-clone = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }
dirs = { workspace = true }
tokio-rustls = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
webpki-roots = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
